version: '3.9'

services:
  alertpm:
    build: .
    image: alertpm
    networks:
      - shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertpm-http.rule=Host(`alert.pm`)"
      - "traefik.http.routers.alertpm-http.entrypoints=web"
      - "traefik.http.services.alertpm-service.loadbalancer.server.port=9000"
      - "traefik.http.routers.alertpm-https.rule=Host(`alert.pm`)"
      - "traefik.http.routers.alertpm-https.tls.certresolver=myresolver"
      - "traefik.http.routers.alertpm-https.entrypoints=websecure"
        #- "traefik.http.services.webstack-https.loadbalancer.server.port=80"
        #- "traefik.http.routers.webstack.middlewares=redirect-to-https" # 新增此行
        #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https" # 新增此行
        #- "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true" # 新增此行
    volumes:
      - ./index.py:/home/code/index.py
networks:
  shared:
    external: true
    name: shared
